WIFI_SSID = ""                # WIFI network to join
WIFI_PASSWORD = ""            # WIFI password
WEATHER_LATITUDE = "51.4780"  # Latitude for weather
WEATHER_LONGITUDE = "0"       # Longitude for weather
TIME_OFFSET = 0               # Time zone
SHOW_ERROR_CODES = 0          # Show error codes on screen
SHOWDATE = 0                  # Show date on bottom
DEBUG = 0                     # Debug mode (run without internet connection)
BRIGHTNESS = 70               # Screen brightness
NTP = "pool.ntp.org"          # ntp server
